"""empty message

Revision ID: 17673e044cde
Revises: 
Create Date: 2023-05-08 23:04:11.875388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17673e044cde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.Column('origin_id', sa.String(length=50), nullable=True),
    sa.Column('origin_user_id', sa.String(length=50), nullable=True),
    sa.Column('origin_msg_id', sa.String(length=50), nullable=True),
    sa.Column('assistant_id', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_assistant_id'), 'messages', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_messages_created_time'), 'messages', ['created_time'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_origin'), 'messages', ['origin'], unique=False)
    op.create_index(op.f('ix_messages_origin_id'), 'messages', ['origin_id'], unique=False)
    op.create_index(op.f('ix_messages_origin_msg_id'), 'messages', ['origin_msg_id'], unique=False)
    op.create_index(op.f('ix_messages_origin_user_id'), 'messages', ['origin_user_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_origin_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_origin_msg_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_origin_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_origin'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_assistant_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
