"""add messages.extra

Revision ID: 2c643d015d9c
Revises: 68adccb5f486
Create Date: 2023-06-02 14:34:45.567879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c643d015d9c'
down_revision = '68adccb5f486'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('extra', sa.String(length=4096), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'extra')
    # ### end Alembic commands ###
