"""message

Revision ID: 2fb845394e80
Revises: b499d0558c73
Create Date: 2023-05-09 22:31:13.200686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb845394e80'
down_revision = 'b499d0558c73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('wxkf_state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wxkf_state',
    sa.Column('key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('states')
    # ### end Alembic commands ###
