"""empty message

Revision ID: 46696f393feb
Revises: 7f10de80312d
Create Date: 2023-05-20 14:50:00.867325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46696f393feb'
down_revision = '7f10de80312d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
