"""empty message

Revision ID: 46efc96b084f
Revises: da70875c9f8b
Create Date: 2023-05-15 23:41:36.593936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46efc96b084f'
down_revision = 'da70875c9f8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('userid', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_created_time'), 'tokens', ['created_time'], unique=False)
    op.create_index(op.f('ix_tokens_expires_at'), 'tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tokens_userid'), 'tokens', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_userid'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_expires_at'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_created_time'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
