"""add user.roles

Revision ID: 505b97cae4c7
Revises: f732a349fb35
Create Date: 2023-05-24 22:16:31.497400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505b97cae4c7'
down_revision = 'f732a349fb35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
