"""fix column spell mistask: history_limit

Revision ID: 68adccb5f486
Revises: 505b97cae4c7
Create Date: 2023-05-25 11:58:52.075038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68adccb5f486'
down_revision = '505b97cae4c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('history_limit', sa.Integer(), nullable=True))
    op.drop_column('robots', 'hisotry_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('hisotry_limit', sa.INTEGER(), nullable=True))
    op.drop_column('robots', 'history_limit')
    # ### end Alembic commands ###
