"""empty message

Revision ID: 69b45a1ec854
Revises: 46efc96b084f
Create Date: 2023-05-16 12:16:36.230026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69b45a1ec854'
down_revision = '46efc96b084f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_routes', sa.Column('owner', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_channel_routes_owner'), 'channel_routes', ['owner'], unique=False)
    op.add_column('channels', sa.Column('owner', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_channels_owner'), 'channels', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channels_owner'), table_name='channels')
    op.drop_column('channels', 'owner')
    op.drop_index(op.f('ix_channel_routes_owner'), table_name='channel_routes')
    op.drop_column('channel_routes', 'owner')
    # ### end Alembic commands ###
