"""empty message

Revision ID: 79eda466d680
Revises: 69b45a1ec854
Create Date: 2023-05-16 15:19:53.499200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79eda466d680'
down_revision = '69b45a1ec854'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_routes', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('channel_routes', sa.Column('created_time', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_channel_routes_created_time'), 'channel_routes', ['created_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_routes_created_time'), table_name='channel_routes')
    op.drop_column('channel_routes', 'created_time')
    op.drop_column('channel_routes', 'name')
    # ### end Alembic commands ###
