"""empty message

Revision ID: 7f10de80312d
Revises: 
Create Date: 2023-05-20 14:46:37.082091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f10de80312d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_routes',
    sa.Column('connector', sa.String(length=50), nullable=False),
    sa.Column('connector_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('connector', 'connector_id')
    )
    op.create_index(op.f('ix_channel_routes_created_time'), 'channel_routes', ['created_time'], unique=False)
    op.create_index(op.f('ix_channel_routes_owner'), 'channel_routes', ['owner'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('robot_id', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channels_created_time'), 'channels', ['created_time'], unique=False)
    op.create_index(op.f('ix_channels_owner'), 'channels', ['owner'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('invalid', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_invalid'), 'invitations', ['invalid'], unique=False)
    op.create_table('knowledges',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledges_created_time'), 'knowledges', ['created_time'], unique=False)
    op.create_index(op.f('ix_knowledges_owner'), 'knowledges', ['owner'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('connector', sa.String(length=50), nullable=True),
    sa.Column('connector_id', sa.String(length=50), nullable=True),
    sa.Column('connector_userid', sa.String(length=50), nullable=True),
    sa.Column('connector_msgid', sa.String(length=50), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.Column('robot_id', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('send_time', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('msgtype', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    op.create_index(op.f('ix_messages_connector'), 'messages', ['connector'], unique=False)
    op.create_index(op.f('ix_messages_connector_id'), 'messages', ['connector_id'], unique=False)
    op.create_index(op.f('ix_messages_connector_msgid'), 'messages', ['connector_msgid'], unique=False)
    op.create_index(op.f('ix_messages_connector_userid'), 'messages', ['connector_userid'], unique=False)
    op.create_index(op.f('ix_messages_created_time'), 'messages', ['created_time'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_robot_id'), 'messages', ['robot_id'], unique=False)
    op.create_index(op.f('ix_messages_send_time'), 'messages', ['send_time'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('template', sa.String(length=4096), nullable=True),
    sa.Column('variables', sa.String(length=4096), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_created_time'), 'prompt_templates', ['created_time'], unique=False)
    op.create_index(op.f('ix_prompt_templates_owner'), 'prompt_templates', ['owner'], unique=False)
    op.create_table('robots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('implement', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=50), nullable=True),
    sa.Column('variables', sa.String(length=4096), nullable=True),
    sa.Column('knowledge_base_id', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_created_time'), 'robots', ['created_time'], unique=False)
    op.create_index(op.f('ix_robots_owner'), 'robots', ['owner'], unique=False)
    op.create_table('states',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tokens',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('userid', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_created_time'), 'tokens', ['created_time'], unique=False)
    op.create_index(op.f('ix_tokens_expires_at'), 'tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_tokens_userid'), 'tokens', ['userid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('salt', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tokens_userid'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_expires_at'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_created_time'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_table('states')
    op.drop_index(op.f('ix_robots_owner'), table_name='robots')
    op.drop_index(op.f('ix_robots_created_time'), table_name='robots')
    op.drop_table('robots')
    op.drop_index(op.f('ix_prompt_templates_owner'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_created_time'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_send_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_robot_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector_userid'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector_msgid'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector'), table_name='messages')
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledges_owner'), table_name='knowledges')
    op.drop_index(op.f('ix_knowledges_created_time'), table_name='knowledges')
    op.drop_table('knowledges')
    op.drop_index(op.f('ix_invitations_invalid'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_channels_owner'), table_name='channels')
    op.drop_index(op.f('ix_channels_created_time'), table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_channel_routes_owner'), table_name='channel_routes')
    op.drop_index(op.f('ix_channel_routes_created_time'), table_name='channel_routes')
    op.drop_table('channel_routes')
    # ### end Alembic commands ###
