"""empty message

Revision ID: 803a232216ec
Revises: b1573fdaad3c
Create Date: 2023-05-11 16:08:19.807549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803a232216ec'
down_revision = 'b1573fdaad3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('implement', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=50), nullable=True),
    sa.Column('config', sa.String(length=4096), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robots')
    # ### end Alembic commands ###
