"""empty message

Revision ID: 8987b37ca570
Revises: eb400b4cbb8a
Create Date: 2023-05-13 14:35:31.637687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8987b37ca570'
down_revision = 'eb400b4cbb8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('salt', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
