"""empty message

Revision ID: b1573fdaad3c
Revises: c904a82d6af7
Create Date: 2023-05-11 16:07:36.215158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1573fdaad3c'
down_revision = 'c904a82d6af7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
