"""empty message

Revision ID: b71a0a7bde6d
Revises: c64bd0fe2614
Create Date: 2023-05-11 17:13:37.975343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71a0a7bde6d'
down_revision = 'c64bd0fe2614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('template', sa.String(length=4096), nullable=True),
    sa.Column('variables', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', 'variables')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
