"""empty message

Revision ID: c64bd0fe2614
Revises: 803a232216ec
Create Date: 2023-05-11 17:13:04.336062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64bd0fe2614'
down_revision = '803a232216ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('prompt_template_id', sa.String(length=50), nullable=True))
    op.add_column('robots', sa.Column('variables', sa.String(length=4096), nullable=True))
    op.drop_column('robots', 'config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robots', sa.Column('config', sa.VARCHAR(length=4096), nullable=True))
    op.drop_column('robots', 'variables')
    op.drop_column('robots', 'prompt_template_id')
    # ### end Alembic commands ###
