"""empty message

Revision ID: c904a82d6af7
Revises: b7552b8ee466
Create Date: 2023-05-11 15:31:21.475529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c904a82d6af7'
down_revision = 'b7552b8ee466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('connector', sa.String(length=50), nullable=True),
    sa.Column('connector_id', sa.String(length=50), nullable=True),
    sa.Column('connector_userid', sa.String(length=50), nullable=True),
    sa.Column('connector_msgid', sa.String(length=50), nullable=True),
    sa.Column('robot_id', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('send_time', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('msgtype', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_connector'), 'messages', ['connector'], unique=False)
    op.create_index(op.f('ix_messages_connector_id'), 'messages', ['connector_id'], unique=False)
    op.create_index(op.f('ix_messages_connector_msgid'), 'messages', ['connector_msgid'], unique=False)
    op.create_index(op.f('ix_messages_connector_userid'), 'messages', ['connector_userid'], unique=False)
    op.create_index(op.f('ix_messages_created_time'), 'messages', ['created_time'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_robot_id'), 'messages', ['robot_id'], unique=False)
    op.create_index(op.f('ix_messages_send_time'), 'messages', ['send_time'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_table('states',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_send_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_robot_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_time'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector_userid'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector_msgid'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_connector'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
