"""empty message

Revision ID: da70875c9f8b
Revises: 8987b37ca570
Create Date: 2023-05-15 23:30:45.023649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da70875c9f8b'
down_revision = '8987b37ca570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('invalid', sa.Boolean(), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_invalid'), 'invitations', ['invalid'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_invitations_invalid'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
