"""empty message

Revision ID: eb400b4cbb8a
Revises: b71a0a7bde6d
Create Date: 2023-05-12 09:33:29.025470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb400b4cbb8a'
down_revision = 'b71a0a7bde6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_routes',
    sa.Column('connector', sa.String(length=50), nullable=False),
    sa.Column('connector_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('connector', 'connector_id')
    )
    op.create_table('channels',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('robot_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('messages', sa.Column('channel_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_messages_channel_id'), 'messages', ['channel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_channel_id'), table_name='messages')
    op.drop_column('messages', 'channel_id')
    op.drop_table('channels')
    op.drop_table('channel_routes')
    # ### end Alembic commands ###
